In [6]:
import pandas as pd
import os
os.chdir("C:/Users/N/Projects/dataset")


legal_info_b = pd.read_excel("data/external/KIKcd_B.20240208.xlsx", dtype={'법정동코드':object})

legal_info_b.head()

        법정동코드    시도명 시군구명 읍면동명  동리명      생성일자  말소일자
0  1100000000  서울특별시  NaN  NaN  NaN  19880423   NaN
1  1111000000  서울특별시  종로구  NaN  NaN  19880423   NaN
2  1111010100  서울특별시  종로구  청운동  NaN  19880423   NaN
3  1111010200  서울특별시  종로구  신교동  NaN  19880423   NaN
4  1111010300  서울특별시  종로구  궁정동  NaN  19880423   NaN

In [8]:
legal_info_b['법정동시군구코드'] = legal_info_b['법정동코드'].str[:5]
legal_info_b['법정동읍면동코드'] = legal_info_b['법정동코드'].str[5:]
legal_info_b.head()

        법정동코드    시도명 시군구명 읍면동명  동리명      생성일자  말소일자 법정동시군구코드 법정동읍면동코드
0  1100000000  서울특별시  NaN  NaN  NaN  19880423   NaN    11000    00000
1  1111000000  서울특별시  종로구  NaN  NaN  19880423   NaN    11110    00000
2  1111010100  서울특별시  종로구  청운동  NaN  19880423   NaN    11110    10100
3  1111010200  서울특별시  종로구  신교동  NaN  19880423   NaN    11110    10200
4  1111010300  서울특별시  종로구  궁정동  NaN  19880423   NaN    11110    10300

In [11]:
# 읍면동이 없는 경우를 제외
legal_info_b = legal_info_b[legal_info_b['법정동읍면동코드'] != "00000"]
legal_info_b = legal_info_b.reset_index(drop = True)
# 필요없는 컬럼 없애기
legal_info_b = legal_info_b[['법정동코드', '시도명', '시군구명', '읍면동명', '동리명', '법정동시군구코드', '법정동읍면동코드']]
legal_info_b.head()

        법정동코드    시도명 시군구명 읍면동명  동리명 법정동시군구코드 법정동읍면동코드
0  1111010100  서울특별시  종로구  청운동  NaN    11110    10100
1  1111010200  서울특별시  종로구  신교동  NaN    11110    10200
2  1111010300  서울특별시  종로구  궁정동  NaN    11110    10300
3  1111010400  서울특별시  종로구  효자동  NaN    11110    10400
4  1111010500  서울특별시  종로구  창성동  NaN    11110    10500

In [20]:
# where(cond, other), 여기서 cond는 조건이고, other는 조건을 만족하지 않는 요소를 대체할 값
legal_info_b = legal_info_b.where(pd.notnull(legal_info_b), "")

legal_info_b['주소'] = legal_info_b['시도명']+" "+legal_info_b['시군구명']+" "+legal_info_b['읍면동명']+" "+legal_info_b['동리명']

legal_info_b['주소'] = legal_info_b['주소'].str.replace('  ', ' ').str.strip()

legal_info_b.head()

        법정동코드    시도명 시군구명 읍면동명 동리명 법정동시군구코드 법정동읍면동코드             주소
0  1111010100  서울특별시  종로구  청운동        11110    10100  서울특별시 종로구 청운동
1  1111010200  서울특별시  종로구  신교동        11110    10200  서울특별시 종로구 신교동
2  1111010300  서울특별시  종로구  궁정동        11110    10300  서울특별시 종로구 궁정동
3  1111010400  서울특별시  종로구  효자동        11110    10400  서울특별시 종로구 효자동
4  1111010500  서울특별시  종로구  창성동        11110    10500  서울특별시 종로구 창성동

In [21]:
legal_info_b.to_csv("data/processed/legal_info_b.csv", index = False)